name: CI
on:
  push:
    branches:
      - '**'

jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: true
#      matrix:
#        node: [10, 12]
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@development
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}